document.addEventListener("DOMContentLoaded",function()
{   
    document.getElementById("show").style.display="block"
    document.querySelector("#expire").onclick=()=>
    {
        if(document.getElementById("show").style.display=="block")
        {
            document.getElementById("show").style.display="none";
        }
        else
        {
            document.getElementById("show").style.display="block";
        }
    }
    document.querySelector("#live").onclick=()=>
    {
        if(document.getElementById("show").style.display=="none")
        {
            document.getElementById("show").style.display="block";
        }
        else
        {
            document.getElementById("show").style.display="none";
        }
    }
//mother information
    document.getElementById("show1").style.display="block"
    document.querySelector("#expire1").onclick=()=>
    {
        if(document.getElementById("show1").style.display=="block")
        {
            document.getElementById("show1").style.display="none";
        }
        else
        {
            document.getElementById("show1").style.display="block";
        }
    }
    document.querySelector("#live1").onclick=()=>
    {
        if(document.getElementById("show1").style.display=="none")
        {
            document.getElementById("show1").style.display="block";
        }
        else
        {
            document.getElementById("show1").style.display="none";
        }
    }
})